# Generated by Django 5.1.2 on 2024-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_alter_ad_car_alter_ad_id_alter_car_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="logo",
            field=models.ImageField(blank=True, upload_to="logos/"),
        ),
    ]
